name: Docker (Test)

on:
  push:
    branches:
      - main
      - test
    paths-ignore:
      - "**/README*"
      - "docs/**"
      - ".github/workflows/*publish*.yml"

env:
  LAMBDA_TAG: kism/archivepodcast:lambda

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build main docker
        run: ./scripts/run_docker_main_adhoc.sh

      - name: Run pyest docker
        run: ./scripts/run_docker_pytest.sh

      - name: Build lambda docker
        run: docker build -f docker/lambda.Dockerfile -t ${{ env.LAMBDA_TAG }} .
