---
name: Ruff

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4

      - name: Install ruff
        run: pipx install ruff

      - name: Add ~/.local/.bin to path for pipx packages
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run ruff
        run: ruff check .
